[package]
name = "oath"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liboath-sys = { git = "https://github.com/littlebenlittle/rust-liboath-sys" }
libc = "0.2"
